wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      Bounding Box Debugger/Images_wandb_delimeter_predictions:
        key: Bounding Box Debugger/Images_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': '0'
          '1': '1'
          '10': A
          '11': B
          '12': C
          '13': D
          '14': E
          '15': F
          '16': G
          '17': H
          '18': I
          '19': J
          '2': '2'
          '20': K
          '21': L
          '22': M
          '23': N
          '24': O
          '25': P
          '26': Q
          '27': R
          '28': S
          '29': T
          '3': '3'
          '30': U
          '31': V
          '32': W
          '33': X
          '34': Y
          '35': Z
          '36': a
          '37': b
          '38': d
          '39': e
          '4': '4'
          '40': f
          '41': g
          '42': h
          '43': n
          '44': q
          '45': r
          '46': t
          '5': '5'
          '6': '6'
          '7': '7'
          '8': '8'
          '9': '9'
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1629259277
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 2
      4: 3.7.11
      5: 0.12.0
      8:
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 64
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: /content/yolov5/models/yolov5s.yaml
data:
  desc: null
  value: /content/drive/MyDrive/OCR Project(SMU)/emnist_data.yaml
data_dict:
  desc: null
  value:
    names:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    - O
    - P
    - Q
    - R
    - S
    - T
    - U
    - V
    - W
    - X
    - Y
    - Z
    - a
    - b
    - d
    - e
    - f
    - g
    - h
    - n
    - q
    - r
    - t
    nc: 47
    test: /content/drive/MyDrive/OCR Project(SMU)/images/test
    train: /content/drive/MyDrive/OCR Project(SMU)/images/train
    val: /content/drive/MyDrive/OCR Project(SMU)/images/val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 10
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: yolo_emnist_det
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/yolo_emnist_det3
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 8
